// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: prime.proto

package prime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrimeCheckerClient is the client API for PrimeChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimeCheckerClient interface {
	IsPrime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (*PrimeResponse, error)
}

type primeCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeCheckerClient(cc grpc.ClientConnInterface) PrimeCheckerClient {
	return &primeCheckerClient{cc}
}

func (c *primeCheckerClient) IsPrime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (*PrimeResponse, error) {
	out := new(PrimeResponse)
	err := c.cc.Invoke(ctx, "/prime.PrimeChecker/IsPrime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimeCheckerServer is the server API for PrimeChecker service.
// All implementations must embed UnimplementedPrimeCheckerServer
// for forward compatibility
type PrimeCheckerServer interface {
	IsPrime(context.Context, *PrimeRequest) (*PrimeResponse, error)
	mustEmbedUnimplementedPrimeCheckerServer()
}

// UnimplementedPrimeCheckerServer must be embedded to have forward compatible implementations.
type UnimplementedPrimeCheckerServer struct {
}

func (UnimplementedPrimeCheckerServer) IsPrime(context.Context, *PrimeRequest) (*PrimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsPrime not implemented")
}
func (UnimplementedPrimeCheckerServer) mustEmbedUnimplementedPrimeCheckerServer() {}

// UnsafePrimeCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimeCheckerServer will
// result in compilation errors.
type UnsafePrimeCheckerServer interface {
	mustEmbedUnimplementedPrimeCheckerServer()
}

func RegisterPrimeCheckerServer(s grpc.ServiceRegistrar, srv PrimeCheckerServer) {
	s.RegisterService(&PrimeChecker_ServiceDesc, srv)
}

func _PrimeChecker_IsPrime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeCheckerServer).IsPrime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prime.PrimeChecker/IsPrime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeCheckerServer).IsPrime(ctx, req.(*PrimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrimeChecker_ServiceDesc is the grpc.ServiceDesc for PrimeChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimeChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeChecker",
	HandlerType: (*PrimeCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsPrime",
			Handler:    _PrimeChecker_IsPrime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prime.proto",
}
